# .travis.yml
language: node_js
node_js:
  - 0.8
before_script:
  - mysql -e 'DROP DATABASE IF EXISTS `goldstone`;CREATE DATABASE `goldstone`;'
  - mysql goldstone < seed.sql
services:
  - redis-server
env:
  - SERVER_HOST='127.0.0.1'